version: '3.8'

services:
  # Our Go application that manages DNS, Certs, and now NPM
  aws-dns-updater:
    build:
      context: .
      dockerfile: Dockerfile
    # image: go-aws-dns-updater:latest
    container_name: aws-dns-updater
    # This ensures it starts after NPM is up, though it has its own retry logic
    depends_on:
      - npm-app
    # Restart if it fails
    restart: unless-stopped
    # Load environment variables from the .env file
    env_file:
      - .env
    # The updater needs to be on the same network to talk to the NPM API
    networks:
      - npm_network
    # Persist its own state files (IP and Cert ARNs)
    volumes:
      - ./updater_data:/app/data

  # The Nginx Proxy Manager application
  npm-app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager-app
    restart: unless-stopped
    # Ports for web traffic and the admin UI
    ports:
      - '80:80'    # Public HTTP Port
      - '443:443'  # Public HTTPS Port
      - '81:81'    # Admin UI
    # Environment variables for NPM's database connection
    environment:
      INITIAL_ADMIN_EMAIL: "${NPM_IDENTITY}"
      INITIAL_ADMIN_PASSWORD: "${NPM_SECRET}"
      # Set to 'true' to disable healthchecks on startup
      DISABLE_IPV6: 'true'
    volumes:
      # Persist NPM's configuration and certificate data
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      - npm_network



# Define the shared network
networks:
  npm_network:
